### ISSUE TITLE
Use constants for json keys

### ISSUE THREAD

**Issue by fraserscottmorrison** [tomlokhorst/swift-json-gen#24]
The json keys I need to use are lowercase with underscores, e.g. "access_token" but I want my properties to be camel case e.g. "accessToken".

Currently I have to change the keys manually in several places, and if I need to regenerate, it'll all be lost.

Could you declare the keys as constants at the top of the extension file so they're just changed in one place. Ideally it'd be best to be able to declare this in the main struct file (somehow...) so that the generated file can remain unmodified.

**Comment by tomlokhorst** [comment]
Yes, I've encountered this quite a few times, where the JSON doesn't quite match what I'd like it to be.

There's currently several ways of handeling this:
1. Create a custom decoder. Just copy/past the generated decoder for this one specific type to your source file and change the string. JsonGen will recognise the existing decoder and won't generate a new one.
2. Add an extension property. Create a new property `var accessToken: String { return access_token }` that simply returns the other one. This can either be directly in the struct, in an extension in the same file, or in a separate file called `SomeName+Extensions.swift`. The +Extensions file is ignored by JsonGen.
3. Create a separate domain model. If the JSON and domain are too different, I would suggest creating a separate domain model, where the JSON is mapped to the domain in pure Swift code.

My preferred method is often the third one, separating the domain model from the JSON model. Often they start off quite similar, but they diverge. In the domain model I want to use enums with associated values, and JSON doesn't support that.

I prefer to keep the mapping from JSON model to domain model in pure Swift code, since that is type-checked by the compiler, instead of relying on putting domain knowledge inside of strings.

**Comment by fraserscottmorrison** [comment]
Good idea, I'll go the seperate domain model approach. Theres going to be a tonne of boilerplate tho...

**Comment by fraserscottmorrison** [comment]
Im going to have the domain model inherit from the json model. I can use custom getters & setters for each property like so 

```
var accessToken:String {
    set {
        super.access_token = newValue
    }
    get {
        return super.access_token
    }
}
```

And I can have additional properties,logic etc in the domain model. Its a shame there's no 'protected' access modifier in Swift - the json model properties can be accessible to other classes. Separating the 2 models has its issues too e.g. decodeJson() can't be accessed directly

**Comment by tomlokhorst** [comment]
My approach for a separate domain model is this:
1. Have a struct that exactly matches the server response:
   
   ``` swift
   struct LoginResponseJson {
     let access_token: String
   
     // Domain rules: both fields are set, or neither is set!
     let first_name: String?
     let last_name: String?
   }
   ```
2. Have a domain struct that encodes all domain rules in types:
   
   ``` swift
   struct LoginResponse {
     let accessToken: String
     let name: Name?
   }
   
   struct Name {
     let first: String
     let last: String
   }
   ```
3. Create mappings in the form of extension initialisers on the domain models:
   
   ``` swift
   extension LoginResponse {
     init(json: LoginResponseJson) {
       self.accessToken = json.access_token
       self.name = Name(json: json)
     }
   }
   
   extension Name {
     init?(json: LoginResponseJson) {
       guard let first = json.first_name, last = json.last_name else {
         return nil
       }
   
       self.first = first
       self.last = last
     }
   }
   ```

This way the domain is completely separate from the JSON and can be used independently. The mappings are a bit of work to write, but they're very important: They implement the domain knowledge that is only encoded in comments in the JSON.

Also the compiler will check if all fields are properly initialized, so you won't accidentally forget to use a field.

**Comment by fraserscottmorrison** [comment]
I like this approach, I’m using it now - the only thing Ive changed is to make the domain model, the only place to reference the json model
eg
extension LoginResponse {
    init(json: AnyObject) throws {
        do {
            let json = try LoginResponseJson.decodeJson(json)
            self.accessToken = json.access_token
            self.name = Name(json: json)
        } catch {
            throw JsonDecodeError.WrongType(rawValue: json, expectedType: "Object")
        }
    }
} 

Thanks for helping with this

**Comment by tomlokhorst** [comment]
Good to read you're using this!

Note that you can probably even remove the `do/catch` block and only rely on the `try` for the decodeJson.
